site_name: TURNTILLBURN
site_url: https://new.turntillburn.ch/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
  language: de

nav:
  - Start: index.md
  - Produkt:
      - Übersicht: product/index.md
      - Pläne: product/plans/index.md
      - Bestellen: product/order/index.md
  - Training:
      - Übersicht: training/index.md
      - Glossar: training/glossar.md
  - Ratgeber:
      - Übersicht: guide/index.md
      - Taping: guide/taping/index.md
      - Finger und Hand: guide/finger_hand/index.md
      - Ellbogen: guide/elbow/index.md
      - Schulter: guide/shoulder/index.md
  - Medizin:
      - Übersicht: medicine/index.md
      - Das Ringband: medicine/a2pulley/index.md
  - Vertical secrets:
      - Übersicht: verticalsecrets/index.md
      - Inhalt: verticalsecrets/content.md
  - Über uns: about.md
  - Kontakt: contact.md

extra_javascript:
  - javascripts/close-fallback.js
  - javascripts/overlib_compat.js
  - javascripts/paypal.js
  - guide/finger_hand/tooltiptexte_mkdocs.js
  - guide/elbow/tooltiptexte_mkdocs.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/tooltips.css

markdown_extensions:
  - admonition
  - attr_list

extra:
  generator: false

copyright: >
  © 2026 TURNTILLBURN, Rotachstrasse 21, CH-8003 Zürich, Tel.: +41 (0)44 451 67 94,
  <a href="mailto:admin@turntillburn.ch">admin@turntillburn.ch</a>

